#!/bin/bash
# ORCCortex Specify-Kit Initialization Script

echo "🚀 Initializing ORCCortex Specify-Kit..."

# Check if specify-kit is installed
if ! command -v specify &> /dev/null; then
    echo "❌ specify-kit not found. Installing with uv..."
    uv pip install specify-kit
fi

# Initialize the specification
echo "📋 Validating specification structure..."

# Check required files
required_files=(
    "project.yaml"
    "overview.md" 
    "architecture.md"
    "api.md"
    "models.md"
    "configuration.md"
    "development.md"
    "security.md"
    "README.md"
)

missing_files=()
for file in "${required_files[@]}"; do
    if [[ ! -f ".specify/$file" ]]; then
        missing_files+=("$file")
    fi
done

if [[ ${#missing_files[@]} -eq 0 ]]; then
    echo "✅ All specification files present"
else
    echo "❌ Missing files: ${missing_files[*]}"
    exit 1
fi

# Validate YAML syntax
echo "🔍 Validating project.yaml..."
if command -v python3 &> /dev/null; then
    python3 -c "import yaml; yaml.safe_load(open('.specify/project.yaml'))" 2>/dev/null
    if [[ $? -eq 0 ]]; then
        echo "✅ project.yaml syntax valid"
    else
        echo "❌ project.yaml syntax error"
        exit 1
    fi
fi

# Generate specification summary
echo "📊 Generating specification summary..."
cat << EOF > .specify/SPECIFICATION_SUMMARY.md
# ORCCortex Specification Summary

**Generated**: $(date)
**Specify-Kit Version**: 1.0
**Project Status**: Development Ready

## Specification Components

$(find .specify -name "*.md" -o -name "*.yaml" | sort | sed 's/\.specify\//- /')

## Quick Stats

- **Total Files**: $(find .specify -type f | wc -l | tr -d ' ')
- **Documentation Files**: $(find .specify -name "*.md" | wc -l | tr -d ' ')
- **Configuration Files**: $(find .specify -name "*.yaml" -o -name "*.yml" | wc -l | tr -d ' ')

## Project Overview

$(head -n 10 .specify/overview.md | tail -n +5)

---
*Generated by specify-kit initialization script*
EOF

echo "✅ Specification initialized successfully!"
echo ""
echo "📖 Next steps:"
echo "   1. Review .specify/README.md for navigation"
echo "   2. Validate with: specify validate"
echo "   3. Generate docs with: specify build"
echo ""
echo "🎯 Your ORCCortex project specification is ready!"