name: ORCCortex
version: 1.0.0
description: Advanced OCR-powered mathematical problem solver that automatically extracts and solves mathematical expressions from PDF documents
author: ORCCortex Team
license: MIT
homepage: https://github.com/ORCCortex/ORCCortex
repository: https://github.com/ORCCortex/ORCCortex

# Project metadata
created: 2025-09-26
updated: 2025-09-26
status: development-ready

# Technology stack
framework: FastAPI
language: Python
version_python: "3.10+"
database: Firebase
cloud: Firebase
ocr_engine: Tesseract
math_engine: SymPy

# Project type and domain
type: web-api
domain: mathematical-computing
category: ocr-solver
tags:
  - ocr
  - mathematics
  - pdf-processing
  - symbolic-math
  - firebase
  - fastapi
  - python